# -*- coding: utf-8 -*-
"""Password Cracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEPuessK5eiUJbtPb6jgtvUZYJ011rY9

## 1️⃣ What this code is about (high‑level)

This script is an **educational brute‑force password demonstration**.

Conceptually it does two things:

1. **Dictionary check**

   * Tries to match the password against:

     * A list of common passwords (`probable-v2-top12000.txt`)
     * A list of names (`middle-names.txt`)
2. **Brute force**

   * If not found in those lists, it tries **every possible character combination** up to `max_nchar` length using:

     * letters
     * digits
     * symbols (depending on how it’s implemented later)

This is **not hacking by itself**, but the same technique is used in attacks, which is why it must only be used for learning on **your own test passwords**.

---

## 2️⃣ Problems with the provided code

### ❌ The code is incomplete

The `bruteforce()` function is cut off and **never returns anything**.

### ❌ External files missing

These files are required but not provided:

```text
probable-v2-top12000.txt
middle-names.txt
```

Without them, the script will crash.

### ❌ Not Colab‑ready

Colab does not have these text files unless you upload them.

### ❌ Inefficient / unsafe defaults

* `max_nchar=8` is enormous for brute force
* No charset is defined yet
* No timing or early stopping logic

---

## 3️⃣ How to run safely in Google Colab (educational demo)

### ✅ What we’ll do instead

* Remove external password lists
* Use a **small charset**
* Use a **short password**
* Make the code runnable and understandable


---

## 5️⃣ How to run this in Google Colab

1. Go to **[https://colab.research.google.com](https://colab.research.google.com)**
2. Click **New Notebook**
3. Paste the code above into a cell
4. Run it
5. Test with a password you choose:

```python
bruteforce("ab1", max_nchar=3)
```

---

## 6️⃣ What this demonstrates (learning goals)

✅ Why short passwords are weak
✅ How password length explodes search space
✅ Why rate‑limiting and hashing are critical
✅ Why brute force becomes impractical quickly

Example:

* 3 characters → thousands of attempts
* 8 characters → **trillions** of attempts

---

## 7️⃣ What NOT to do

❌ Do not use this on:

* Websites
* Accounts
* Other people’s data
* Systems without permission

That would be illegal and unethical.

---
"""

# ---------------------------
# 💥 Password Cr*cker Code 💥
# ---------------------------

import string
from itertools import product
from time import time
from numpy import loadtxt


def product_loop(password, generator):
    for p in generator:
        if ''.join(p) == password:
            print('\nPassword:', ''.join(p))
            return ''.join(p)
    return False


def bruteforce(password, max_nchar=8):
    """Password brute-force algorithm.
    Parameters
    ----------
    password : string
        To-be-found password.
    max_nchar : int
        Maximum number of characters of password.
    Return
    ------
    bruteforce_password : string
        Brute-forced password
    """
    print('1 Comparing with most common passwords / first names')
    common_pass = loadtxt('/content/Top12Thousand-probable-v2.txt', dtype=str)
    common_names = loadtxt('/content/middle-names.txt', dtype=str)
    cp = [c for c in common_pass if c == password]
    cn = [c for c in common_names if c == password]
    cnl = [c.lower() for c in common_names if c.lower() == password]

# ---------------------------
# 💥 Password Cr*cker Code 💥
# (Educational use only)
# ---------------------------

import string
from itertools import product
from time import time
from numpy import loadtxt


def product_loop(password, generator):
    """
    Loop through generated password combinations
    """
    for p in generator:
        if ''.join(p) == password:
            print('\nPassword found:', ''.join(p))
            return ''.join(p)
    return False


def bruteforce(password, max_nchar=5):
    """
    Password brute-force algorithm (educational).

    Parameters
    ----------
    password : string
        Password to be tested (must be your own).
    max_nchar : int
        Maximum password length to try.

    Returns
    -------
    string or None
    """
    start = time()

    print('1) Comparing with most common passwords / first names')

    # Load dictionary files (must exist in /content/)
    common_pass = loadtxt('/content/Top12Thousand-probable-v2.txt', dtype=str)
    common_names = loadtxt('/content/middle-names.txt', dtype=str, usecols=(0,))

    # Dictionary checks
    if password in common_pass:
        print("Password found in common passwords list!")
        return password

    if password in common_names:
        print("Password found in names list!")
        return password

    if password.lower() in [n.lower() for n in common_names]:
        print("Password found in lowercase names list!")
        return password

    print("Not found in dictionaries.")
    print("2) Starting brute-force search...")

    # Character set for brute force
    charset = string.ascii_lowercase + string.digits

    # Brute-force phase
    for length in range(1, max_nchar + 1):
        print(f"Trying passwords of length {length}...")
        generator = product(charset, repeat=length)
        result = product_loop(password, generator)
        if result:
            print(f"Time taken: {time() - start:.2f} seconds")
            return result

    print("Password not found.")
    print(f"Time taken: {time() - start:.2f} seconds")
    return None
result = bruteforce("ab1", max_nchar=3)
print("Returned value:", result)

import string
from itertools import product
from time import time

def bruteforce(password, max_nchar=3):
    """
    Educational brute-force demo.
    Only use on passwords you own.
    """
    charset = string.ascii_lowercase + string.digits
    start = time()

    print(f"Trying to brute-force password of length ≤ {max_nchar}")

    for length in range(1, max_nchar + 1):
        for guess in product(charset, repeat=length):
            guess = ''.join(guess)
            if guess == password:
                print(f"\nPassword found: {guess}")
                print(f"Time taken: {time() - start:.2f} seconds")
                return guess

    print("Password not found")
    return None